# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\coding\python\P2MM-Entanglement\src\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.consoleTab = QtWidgets.QWidget()
        self.consoleTab.setObjectName("consoleTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.consoleTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.console_output = QtWidgets.QTextEdit(self.consoleTab)
        self.console_output.setReadOnly(True)
        self.console_output.setObjectName("console_output")
        self.verticalLayout_2.addWidget(self.console_output)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.command_line = QtWidgets.QLineEdit(self.consoleTab)
        self.command_line.setText("")
        self.command_line.setObjectName("command_line")
        self.horizontalLayout.addWidget(self.command_line)
        self.send_button = QtWidgets.QPushButton(self.consoleTab)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.start_button = QtWidgets.QPushButton(self.consoleTab)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        self.tabWidget.addTab(self.consoleTab, "")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.configTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.configTabVerticalLayout = QtWidgets.QVBoxLayout()
        self.configTabVerticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.configTabVerticalLayout.setObjectName("configTabVerticalLayout")
        self.configArea = QtWidgets.QScrollArea(self.configTab)
        self.configArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.configArea.setWidgetResizable(True)
        self.configArea.setObjectName("configArea")
        self.configScrollAreaWidget = QtWidgets.QWidget()
        self.configScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 537, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configScrollAreaWidget.sizePolicy().hasHeightForWidth())
        self.configScrollAreaWidget.setSizePolicy(sizePolicy)
        self.configScrollAreaWidget.setObjectName("configScrollAreaWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.configScrollAreaWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.configArea.setWidget(self.configScrollAreaWidget)
        self.configTabVerticalLayout.addWidget(self.configArea)
        self.ConfigTabActionsLayout = QtWidgets.QHBoxLayout()
        self.ConfigTabActionsLayout.setContentsMargins(10, -1, 10, -1)
        self.ConfigTabActionsLayout.setSpacing(20)
        self.ConfigTabActionsLayout.setObjectName("ConfigTabActionsLayout")
        self.SaveButton = QtWidgets.QPushButton(self.configTab)
        self.SaveButton.setObjectName("SaveButton")
        self.ConfigTabActionsLayout.addWidget(self.SaveButton)
        self.ResetButton = QtWidgets.QPushButton(self.configTab)
        self.ResetButton.setObjectName("ResetButton")
        self.ConfigTabActionsLayout.addWidget(self.ResetButton)
        self.configTabVerticalLayout.addLayout(self.ConfigTabActionsLayout)
        self.verticalLayout_3.addLayout(self.configTabVerticalLayout)
        self.tabWidget.addTab(self.configTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P2MM Launcher"))
        self.console_output.setPlaceholderText(_translate("MainWindow", "CONSOLE"))
        self.command_line.setPlaceholderText(_translate("MainWindow", "Console Command"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.consoleTab), _translate("MainWindow", "Console"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Configs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
